name: Build

on:
  pull_request:

      
jobs:
  build:
    name: Build
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: 18
          cache: npm
          
      - name: Get npm version
        run: npm --version;

      - name: get node version
        run: node --version;
